# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: colony-relay

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/colony-relay/
    binary: colony-relay
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

release:
  draft: true
  replace_existing_artifacts: true

homebrew_casks:
  - name: colony-relay
    binaries:
      - colony-relay
    repository:
      owner: ff6347
      name: homebrew-tap
      token: "{{ .Env.BREWTAP_TOKEN }}"
    directory: .
    homepage: "https://github.com/ff6347/colony-relay"
    description: "Message relay for agent-to-agent communication"
